version: '3.7'

services:
  db:
    container_name: flask2_db
    image: mysql:5.7
    # 環境変数読み込み
    env_file:
      - ./secret/.env
    environment:
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
      - db_sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  app:
    container_name: flask2
    # Dockerfileの存在するディレクトリを指定
    build: 
      context: ./build/app
      dockerfile: ./Dockerfile
      args:
          project_dir: "/var/www/ConvertImageToExcel/"
    # ポートフォワーディング設定
    ports: 
      - "3031:3031" # uwsgi
    # リンク
    links:
      - db
    # データの永続化
    volumes:
      - ".:/var/www/ConvertImageToExcel"
    # 環境変数の設定
    environment:
      TZ: Asia/Tokyo
      FLASK_ENV: "produciton"
    #ファイルから環境変数設定
    env_file:
      - ./secret/.env
    # 起動したままにする
    # tty: true

  web:
    container_name: flask2_web
    build: 
      context: ./build/web
      dockerfile: ./Dockerfile_no-ssl
    volumes:
      - ./build/web/nginx.conf_production_no-ssl:/etc/nginx/nginx.conf
      # nginxのログをホストOSの /tmp/nginx_log に出力する
      #- ./build/web/nginx_log:/var/log/nginx
    # 環境変数読み込み
    env_file:
      - ./secret/.env
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"
    # 依存関係
    depends_on:
      - app


# ボリュームの永続化
volumes:
  db_data:
  db_sql:
