version: '3'

networks:
  app-net:
    driver: bridge

services:
  app:
    container_name: flask2
    # Dockerfileの存在するディレクトリを指定
    build: 
      context: ./build/app
      dockerfile: ./Dockerfile
      args:
          project_dir: "/var/www/ConvertImageToExcel/"
    # ポートフォワーディング設定
    ports: 
      - "3031:3031" # uwsgi
    # リンク
    links:
      - db
    # データの永続化
    volumes:
      - ".:/var/www/ConvertImageToExcel"
    # 環境変数の設定
    environment:
      TZ: Asia/Tokyo
      FLASK_ENV: "produciton"
        
    env_file:
      - ./secret/.env
    # 起動したままにする
    # tty: true
    # ネットワークの設定
    networks:
      - app-net
  db:
    container_name: flask2_db
    image: mysql:5.7
    # 環境変数読み込み
    env_file:
      - ./secret/.env
    environment:
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./build/db/data:/var/lib/mysql
      - ./build/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    # ネットワークの設定
    networks:
      - app-net
  web:
    container_name: flask2_web
    build: 
      context: ./build/web
      dockerfile: ./Dockerfile
    volumes:
      - ./build/web/nginx.conf:/etc/nginx/nginx.conf
      # nginxのログをホストOSの /tmp/nginx_log に出力する
      - /build/web/tmp/nginx_log:/var/log/nginx
    links:
      - app
    ports:
      - "4231:80"
    environment:
      TZ: "Asia/Tokyo"
    # ネットワークの設定
    networks:
      - app-net
